name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - master
      - default
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master
      - default

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      # Erstelle Bereitstellungsverzeichnis
      - name: Erstelle Deploy-Verzeichnis
        run: |
          mkdir -p deploy
          
      # Kopiere die github-pages Inhalte direkt in das Bereitstellungsverzeichnis
      - name: Kopiere Static Files
        run: |
          cp -r github-pages/* deploy/
          cp github-pages/.nojekyll deploy/ 2>/dev/null || touch deploy/.nojekyll
          cp staticwebapp.config.json deploy/
          cp skip-build.txt deploy/
          cp azure.yml deploy/
          
      # Stelle sicher, dass keine Jekyll-Build ausgeführt wird
      - name: Deaktiviere Jekyll
        run: |
          touch deploy/.nojekyll
          echo "Skip Jekyll processing" > deploy/.skipjekyll
          
      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/deploy" # Bereitstellungsverzeichnis
          output_location: "" # Built app content directory - blank for static apps without build
          skip_app_build: true # Skip build process as we're using a static HTML app
          config_file_location: "/deploy" # Location of the staticwebapp.config.json file
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"